before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: "shiftpart"
    ldflags:
      - "-s -w -X main.Version='{{.Version}}' -X main.GitCommit={{.Commit}}"
#      - freebsd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - amd64
      - 386
      - arm64
    goarm:
      - 6
      - 7
    main: ./
    binary: shiftpart
    tags:
      - release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "shiftpart{{ .Version }}_{{ .Os }}_{{ .Arch }}{{.Arm}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
